<?php

/**
 * Custom FileInfo wrapper.
 *
 * @version 1.0.0
 * @author Nathan Bishop (nbish11)
 * @copyright 2016 Nathan Bishop
 * @license MIT
 *
 * @property string $directory
 * @property string $basename
 * @property string $extension
 * @property string $filename
 * @property string $mimetype
 */
class FileInfo
{
    /**
     * If a mimetype was NOT found this will be returned; which in
     * most cases is more than sufficient.
     *
     * @var string
     */
    const DEFAULT_MIMETYPE = 'application/octet-stream';

    /**
     * The file to check for.
     *
     * @var string
     */
    private $file;

    /**
     * Constructs a new `FileInfo` instance.
     *
     * @param string  $file   Path to file.
     * @param boolean $exists Check if file exists.
     */
    public function __construct($file, $exists = false)
    {
        if ( ! is_string($file)) {
            throw new InvalidArgumentException('FileInfo expects a string.');
        }

        if ($exists && !file_exists($file)) {
            throw new Exception('The file was not found at the following location: ' . $file);
        }

        $this->file = $file;
    }

    /**
     * Retrieve the directory of the file.
     *
     * @return string E.g. C:/wamp/www/FileInfo/src
     */
    public function getDirectory()
    {
        return dirname($this->file);
    }

    /**
     * Retrieve the filename and the extension.
     *
     * @return string E.g. FileInfo.php
     */
    public function getBaseName()
    {
        return basename($this->file);
    }

    /**
     * The extension of the file.
     *
     * @return string E.g. php
     */
    public function getExtension()
    {
        return substr(strrchr($this->getBasename(), '.'), 1);
    }

    /**
     * The basename without the extension.
     *
     * @return string E.g. FileInfo
     */
    public function getFileName()
    {
        return basename($this->file, '.' . $this->getExtension());
    }

    /**
     * The content-type/mimetype of the file.
     *
     * @return string E.g. application/octet-stream
     */
    public function getMimeType()
    {
        $ext = $this->getExtension();
        $mimes = $this->getMimeTypes();

        return isset($mimes[$ext]) ? $mimes[$ext] : self::DEFAULT_MIMETYPE;
    }

    /**
     * Checks if an arbitrary property exists.
     *
     * @param  string $key
     * @return boolean
     */
    public function __isset($key)
    {
        $allowed = array(
            'directory',
            'basename',
            'extension',
            'filename',
            'mimetype'
        );

        return in_array(strtolower($key), $allowed);
    }

    /**
     * Retrieve an arbitrary property.
     *
     * @param  string $key
     * @return string
     */
    public function __get($key)
    {
        switch (strtolower($key)) {
            case 'directory':
                return $this->getDirectory();

            case 'basename':
                return $this->getBaseName();

            case 'extension':
                return $this->getExtension();

            case 'filename':
                return $this->getFileName();

            case 'mimetype':
                return $this->getMimeType();

            default:
                return null;
        }
    }

    /**
     * Retrieve a list of supported mime-types.
     *
     * Based on Apache's "mime.types" file.
     *
     * @return array
     */
    private function getMimeTypes()
    {
        return array(
            // "application/*"
            '123'   => 'application/vnd.lotus-1-2-3',
            '7z'    => 'application/x-7z-compressed',
            'aab'   => 'application/x-authorware-bin',
            'aam'   => 'application/x-authorware-map',
            'aas'   => 'application/x-authorware-seg',
            'abw'   => 'application/x-abiword',
            'ac'    => 'application/pkix-attr-cert',
            'acc'   => 'application/vnd.americandynamics.acc',
            'ace'   => 'application/x-ace-compressed',
            'acu'   => 'application/vnd.acucobol',
            'acutc' => 'application/vnd.acucorp',
            'aep'   => 'application/vnd.audiograph',
            'afm'   => 'application/x-font-type1',
            'afp'   => 'application/vnd.ibm.modcap',
            'ahead' => 'application/vnd.ahead.space',
            'ai'    => 'application/postscript',
            'air'   => 'application/vnd.adobe.air-application-installer-package+zip',
            'ait'   => 'application/vnd.dvb.ait',
            'ami'   => 'application/vnd.amiga.ami',
            'apk'   => 'application/vnd.android.package-archive',
            'application' => 'application/x-ms-application',
            'apr'   => 'application/vnd.lotus-approach',
            'arc'   => 'application/x-freearc',
            'asc'   => 'application/pgp-signature',
            'aso'   => 'application/vnd.accpac.simply.aso',
            'atc'   => 'application/vnd.acucorp',
            'atom'  => 'application/atom+xml',
            'atomcat' => 'application/atomcat+xml',
            'atomsvc' => 'application/atomsvc+xml',
            'atx'   => 'application/vnd.antix.game-component',
            'aw'    => 'application/applixware',
            'azf'   => 'application/vnd.airzip.filesecure.azf',
            'azs'   => 'application/vnd.airzip.filesecure.azs',
            'azw'   => 'application/vnd.amazon.ebook',
            'bat'   => 'application/x-msdownload',
            'bcpio' => 'application/x-bcpio',
            'bdf'   => 'application/x-font-bdf',
            'bdm'   => 'application/vnd.syncml.dm+wbxml',
            'bed'   => 'application/vnd.realvnc.bed',
            'bh2'   => 'application/vnd.fujitsu.oasysprs',
            'bin'   => 'application/octet-stream',
            'blb'   => 'application/x-blorb',
            'blorb' => 'application/x-blorb',
            'bmi'   => 'application/vnd.bmi',
            'book'  => 'application/vnd.framemaker',
            'box'   => 'application/vnd.previewsystems.box',
            'boz'   => 'application/x-bzip2',
            'bpk'   => 'application/octet-stream',
            'bz'    => 'application/x-bzip',
            'bz2'   => 'application/x-bzip2',
            'c11amc' => 'application/vnd.cluetrust.cartomobile-config',
            'c11amz' => 'application/vnd.cluetrust.cartomobile-config-pkg',
            'c4d'   => 'application/vnd.clonk.c4group',
            'c4f'   => 'application/vnd.clonk.c4group',
            'c4g'   => 'application/vnd.clonk.c4group',
            'c4p'   => 'application/vnd.clonk.c4group',
            'c4u'   => 'application/vnd.clonk.c4group',
            'cab'   => 'application/vnd.ms-cab-compressed',
            'cap'   => 'application/vnd.tcpdump.pcap',
            'car'   => 'application/vnd.curl.car',
            'cat'   => 'application/vnd.ms-pki.seccat',
            'cb7'   => 'application/x-cbr',
            'cba'   => 'application/x-cbr',
            'cbr'   => 'application/x-cbr',
            'cbt'   => 'application/x-cbr',
            'cbz'   => 'application/x-cbr',
            'cct'   => 'application/x-director',
            'ccxml' => 'application/ccxml+xml',
            'cdbcmsg' => 'application/vnd.contact.cmsg',
            'cdf'   => 'application/x-netcdf',
            'cdkey' => 'application/vnd.mediastation.cdkey',
            'cdmia' => 'application/cdmi-capability',
            'cdmic' => 'application/cdmi-container',
            'cdmid' => 'application/cdmi-domain',
            'cdmio' => 'application/cdmi-object',
            'cdmiq' => 'application/cdmi-queue',
            'cdxml' => 'application/vnd.chemdraw+xml',
            'cdy'   => 'application/vnd.cinderella',
            'cer'   => 'application/pkix-cert',
            'cfs'   => 'application/x-cfs-compressed',
            'chat'  => 'application/x-chat',
            'chm'   => 'application/vnd.ms-htmlhelp',
            'chrt'  => 'application/vnd.kde.kchart',
            'cii'   => 'application/vnd.anser-web-certificate-issue-initiation',
            'cil'   => 'application/vnd.ms-artgalry',
            'cla'   => 'application/vnd.claymore',
            'class' => 'application/java-vm',
            'clkk'  => 'application/vnd.crick.clicker.keyboard',
            'clkp'  => 'application/vnd.crick.clicker.palette',
            'clkt'  => 'application/vnd.crick.clicker.template',
            'clkw'  => 'application/vnd.crick.clicker.wordbank',
            'clkx'  => 'application/vnd.crick.clicker',
            'clp'   => 'application/x-msclip',
            'cmc'   => 'application/vnd.cosmocaller',
            'cmp'   => 'application/vnd.yellowriver-custom-menu',
            'cod'   => 'application/vnd.rim.cod',
            'com'   => 'application/x-msdownload',
            'cpio'  => 'application/x-cpio',
            'cpt'   => 'application/mac-compactpro',
            'crd'   => 'application/x-mscardfile',
            'crl'   => 'application/pkix-crl',
            'crt'   => 'application/x-x509-ca-cert',
            'cryptonote' => 'application/vnd.rig.cryptonote',
            'csh'   => 'application/x-csh',
            'csp'   => 'application/vnd.commonspace',
            'cst'   => 'application/x-director',
            'cu'    => 'application/cu-seeme',
            'cww'   => 'application/prs.cww',
            'cxt'   => 'application/x-director',
            'daf'   => 'application/vnd.mobius.daf',
            'dart'  => 'application/vnd.dart',
            'dataless' => 'application/vnd.fdsn.seed',
            'davmount' => 'application/davmount+xml',
            'dbk'   => 'application/docbook+xml',
            'dcr'   => 'application/x-director',
            'dd2'   => 'application/vnd.oma.dd2+xml',
            'ddd'   => 'application/vnd.fujixerox.ddd',
            'deb'   => 'application/x-debian-package',
            'deploy' => 'application/octet-stream',
            'der'   => 'application/x-x509-ca-cert',
            'dfac'  => 'application/vnd.dreamfactory',
            'dgc'   => 'application/x-dgc-compressed',
            'dir'   => 'application/x-director',
            'dis'   => 'application/vnd.mobius.dis',
            'dist'  => 'application/octet-stream',
            'distz' => 'application/octet-stream',
            'dll'   => 'application/x-msdownload',
            'dmg'   => 'application/x-apple-diskimage',
            'dmp'   => 'application/vnd.tcpdump.pcap',
            'dms'   => 'application/octet-stream',
            'dna'   => 'application/vnd.dna',
            'doc'   => 'application/msword',
            'docm'  => 'application/vnd.ms-word.document.macroenabled.12',
            'docx'  => 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
            'dot'   => 'application/msword',
            'dotm'  => 'application/vnd.ms-word.template.macroenabled.12',
            'dotx'  => 'application/vnd.openxmlformats-officedocument.wordprocessingml.template',
            'dp'    => 'application/vnd.osgi.dp',
            'dpg'   => 'application/vnd.dpgraph',
            'dssc'  => 'application/dssc+der',
            'dtb'   => 'application/x-dtbook+xml',
            'dtd'   => 'application/xml-dtd',
            'dump'  => 'application/octet-stream',
            'dvi'   => 'application/x-dvi',
            'dxp'   => 'application/vnd.spotfire.dxp',
            'dxr'   => 'application/x-director',
            'ecma'  => 'application/ecmascript',
            'edm'   => 'application/vnd.novadigm.edm',
            'edx'   => 'application/vnd.novadigm.edx',
            'efif'  => 'application/vnd.picsel',
            'ei6'   => 'application/vnd.pg.osasli',
            'elc'   => 'application/octet-stream',
            'emf'   => 'application/x-msmetafile',
            'emma'  => 'application/emma+xml',
            'emz'   => 'application/x-msmetafile',
            'eot'   => 'application/vnd.ms-fontobject',
            'eps'   => 'application/postscript',
            'epub'  => 'application/epub+zip',
            'es3'   => 'application/vnd.eszigno3+xml',
            'esa'   => 'application/vnd.osgi.subsystem',
            'esf'   => 'application/vnd.epson.esf',
            'et3'   => 'application/vnd.eszigno3+xml',
            'eva'   => 'application/x-eva',
            'evy'   => 'application/x-envoy',
            'exe'   => 'application/x-msdownload',
            'exi'   => 'application/exi',
            'ext'   => 'application/vnd.novadigm.ext',
            'ez'    => 'application/andrew-inset',
            'ez2'   => 'application/vnd.ezpix-album',
            'ez3'   => 'application/vnd.ezpix-package',
            'fcdt'  => 'application/vnd.adobe.formscentral.fcdt',
            'fcs'   => 'application/vnd.isac.fcs',
            'fdf'   => 'application/vnd.fdf',
            'fe_launch' => 'application/vnd.denovo.fcselayout-link',
            'fg5'   => 'application/vnd.fujitsu.oasysgp',
            'fgd'   => 'application/x-director',
            'fig'   => 'application/x-xfig',
            'flo'   => 'application/vnd.micrografx.flo',
            'flw'   => 'application/vnd.kde.kivio',
            'fm'    => 'application/vnd.framemaker',
            'fnc'   => 'application/vnd.frogans.fnc',
            'frame' => 'application/vnd.framemaker',
            'fsc'   => 'application/vnd.fsc.weblaunch',
            'ftc'   => 'application/vnd.fluxtime.clip',
            'fti'   => 'application/vnd.anser-web-funds-transfer-initiation',
            'fxp'   => 'application/vnd.adobe.fxp',
            'fxpl'  => 'application/vnd.adobe.fxp',
            'fzs'   => 'application/vnd.fuzzysheet',
            'g2w'   => 'application/vnd.geoplan',
            'g3w'   => 'application/vnd.geospace',
            'gac'   => 'application/vnd.groove-account',
            'gam'   => 'application/x-tads',
            'gbr'   => 'application/rpki-ghostbusters',
            'gca'   => 'application/x-gca-compressed',
            'geo'   => 'application/vnd.dynageo',
            'gex'   => 'application/vnd.geometry-explorer',
            'ggb'   => 'application/vnd.geogebra.file',
            'ggt'   => 'application/vnd.geogebra.tool',
            'ghf'   => 'application/vnd.groove-help',
            'gim'   => 'application/vnd.groove-identity-message',
            'gml'   => 'application/gml+xml',
            'gmx'   => 'application/vnd.gmx',
            'gnumeric' => 'application/x-gnumeric',
            'gph'   => 'application/vnd.flographit',
            'gpx'   => 'application/gpx+xml',
            'gqf'   => 'application/vnd.grafeq',
            'gqs'   => 'application/vnd.grafeq',
            'gram'  => 'application/srgs',
            'gramps' => 'application/x-gramps-xml',
            'gre'   => 'application/vnd.geometry-explorer',
            'grv'   => 'application/vnd.groove-injector',
            'grxml' => 'application/srgs+xml',
            'gsf'   => 'application/x-font-ghostscript',
            'gtar'  => 'application/x-gtar',
            'gtm'   => 'application/vnd.groove-tool-message',
            'gxf'   => 'application/gxf',
            'gxt'   => 'application/vnd.geonext',
            'hal'   => 'application/vnd.hal+xml',
            'hbci'  => 'application/vnd.hbci',
            'hdf'   => 'application/x-hdf',
            'hlp'   => 'application/winhlp',
            'hpgl'  => 'application/vnd.hp-hpgl',
            'hpid'  => 'application/vnd.hp-hpid',
            'hps'   => 'application/vnd.hp-hps',
            'hqx'   => 'application/mac-binhex40',
            'htke'  => 'application/vnd.kenameaapp',
            'hvd'   => 'application/vnd.yamaha.hv-dic',
            'hvp'   => 'application/vnd.yamaha.hv-voice',
            'hvs'   => 'application/vnd.yamaha.hv-script',
            'i2g'   => 'application/vnd.intergeo',
            'icc'   => 'application/vnd.iccprofile',
            'icm'   => 'application/vnd.iccprofile',
            'ifm'   => 'application/vnd.shana.informed.formdata',
            'igl'   => 'application/vnd.igloader',
            'igm'   => 'application/vnd.insors.igm',
            'igx'   => 'application/vnd.micrografx.igx',
            'iif'   => 'application/vnd.shana.informed.interchange',
            'imp'   => 'application/vnd.accpac.simply.imp',
            'ims'   => 'application/vnd.ms-ims',
            'ink'   => 'application/inkml+xml',
            'inkml' => 'application/inkml+xml',
            'install' => 'application/x-install-instructions',
            'iota'  => 'application/vnd.astraea-software.iota',
            'ipfix' => 'application/ipfix',
            'ipk'   => 'application/vnd.shana.informed.package',
            'irm'   => 'application/vnd.ibm.rights-management',
            'irp'   => 'application/vnd.irepository.package+xml',
            'iso'   => 'application/x-iso9660-image',
            'itp'   => 'application/vnd.shana.informed.formtemplate',
            'ivp'   => 'application/vnd.immervision-ivp',
            'ivu'   => 'application/vnd.immervision-ivu',
            'jam'   => 'application/vnd.jam',
            'jar'   => 'application/java-archive',
            'jisp'  => 'application/vnd.jisp',
            'jlt'   => 'application/vnd.hp-jlyt',
            'jnlp'  => 'application/x-java-jnlp-file',
            'joda'  => 'application/vnd.joost.joda-archive',
            'js'    => 'application/javascript',
            'json'  => 'application/json',
            'jsonml'    => 'application/jsonml+json',
            'karbon'    => 'application/vnd.kde.karbon',
            'kfo'   => 'application/vnd.kde.kformula',
            'kia'   => 'application/vnd.kidspiration',
            'kml'   => 'application/vnd.google-earth.kml+xml',
            'kmz'   => 'application/vnd.google-earth.kmz',
            'kne'   => 'application/vnd.kinar',
            'knp'   => 'application/vnd.kinar',
            'kon'   => 'application/vnd.kde.kontour',
            'kpr'   => 'application/vnd.kde.kpresenter',
            'kpt'   => 'application/vnd.kde.kpresenter',
            'kpxx'  => 'application/vnd.ds-keypoint',
            'ksp'   => 'application/vnd.kde.kspread',
            'ktr'   => 'application/vnd.kahootz',
            'ktz'   => 'application/vnd.kahootz',
            'kwd'   => 'application/vnd.kde.kword',
            'kwt'   => 'application/vnd.kde.kword',
            'lasxml'    => 'application/vnd.las.las+xml',
            'latex' => 'application/x-latex',
            'lbd'   => 'application/vnd.llamagraphics.life-balance.desktop',
            'lbe'   => 'application/vnd.llamagraphics.life-balance.exchange+xml',
            'les'   => 'application/vnd.hhe.lesson-player',
            'lha'   => 'application/x-lzh-compressed',
            'link66' => 'application/vnd.route66.link66+xml',
            'list3820'  => 'application/vnd.ibm.modcap',
            'listafp'   => 'application/vnd.ibm.modcap',
            'lnk'   => 'application/x-ms-shortcut',
            'lostxml'   => 'application/lost+xml',
            'lrf'   => 'application/octet-stream',
            'lrm'   => 'application/vnd.ms-lrm',
            'ltf'   => 'application/vnd.frogans.ltf',
            'lwp'   => 'application/vnd.lotus-wordpro',
            'lzh'   => 'application/x-lzh-compressed',
            'm13'   => 'application/x-msmediaview',
            'm14'   => 'application/x-msmediaview',
            'm21'   => 'application/mp21',
            'm3u8'  => 'application/vnd.apple.mpegurl',
            'ma'    => 'application/mathematica',
            'mads'  => 'application/mads+xml',
            'mag'   => 'application/vnd.ecowin.chart',
            'maker'     => 'application/vnd.framemaker',
            'mar'   => 'application/octet-stream',
            'mathml'    => 'application/mathml+xml',
            'mb'    => 'application/mathematica',
            'mbk'   => 'application/vnd.mobius.mbk',
            'mbox'  => 'application/mbox',
            'mc1'   => 'application/vnd.medcalcdata',
            'mcd'   => 'application/vnd.mcd',
            'mdb'   => 'application/x-msaccess',
            'meta4'     => 'application/metalink4+xml',
            'metalink'  => 'application/metalink+xml',
            'mets'  => 'application/mets+xml',
            'mfm'   => 'application/vnd.mfmp',
            'mft'   => 'application/rpki-manifest',
            'mgp'   => 'application/vnd.osgeo.mapguide.package',
            'mgz'   => 'application/vnd.proteus.magazine',
            'mie'   => 'application/x-mie',
            'mif'   => 'application/vnd.mif',
            'mlp'   => 'application/vnd.dolby.mlp',
            'mmd'   => 'application/vnd.chipnuts.karaoke-mmd',
            'mmf'   => 'application/vnd.smaf',
            'mny'   => 'application/x-msmoney',
            'mobi'  => 'application/x-mobipocket-ebook',
            'mods'  => 'application/mods+xml',
            'mp21'  => 'application/mp21',
            'mp4s'  => 'application/mp4',
            'mpc'   => 'application/vnd.mophun.certificate',
            'mpkg'  => 'application/vnd.apple.installer+xml',
            'mpm'   => 'application/vnd.blueice.multipass',
            'mpn'   => 'application/vnd.mophun.application',
            'mpp'   => 'application/vnd.ms-project',
            'mpt'   => 'application/vnd.ms-project',
            'mpy'   => 'application/vnd.ibm.minipay',
            'mqy'   => 'application/vnd.mobius.mqy',
            'mrc'   => 'application/marc',
            'mrcx'  => 'application/marcxml+xml',
            'mscml' => 'application/mediaservercontrol+xml',
            'mseed' => 'application/vnd.fdsn.mseed',
            'mseq'  => 'application/vnd.mseq',
            'msf'   => 'application/vnd.epson.msf',
            'msi'   => 'application/x-msdownload',
            'msl'   => 'application/vnd.mobius.msl',
            'msty'  => 'application/vnd.muvee.style',
            'mus'   => 'application/vnd.musician',
            'musicxml'  => 'application/vnd.recordare.musicxml+xml',
            'mvb'   => 'application/x-msmediaview',
            'mwf'   => 'application/vnd.mfer',
            'mxf'   => 'application/mxf',
            'mxl'   => 'application/vnd.recordare.musicxml',
            'mxml'  => 'application/xv+xml',
            'mxs'   => 'application/vnd.triscape.mxs',
            'n-gage'    => 'application/vnd.nokia.n-gage.symbian.install',
            'nb'    => 'application/mathematica',
            'nbp'   => 'application/vnd.wolfram.player',
            'nc'    => 'application/x-netcdf',
            'ncx'   => 'application/x-dtbncx+xml',
            'ngdat' => 'application/vnd.nokia.n-gage.data',
            'nitf'  => 'application/vnd.nitf',
            'nlu'   => 'application/vnd.neurolanguage.nlu',
            'nml'   => 'application/vnd.enliven',
            'nnd'   => 'application/vnd.noblenet-directory',
            'nns'   => 'application/vnd.noblenet-sealer',
            'nnw'   => 'application/vnd.noblenet-web',
            'nsc'   => 'application/x-conference',
            'nsf'   => 'application/vnd.lotus-notes',
            'ntf'   => 'application/vnd.nitf',
            'nzb'   => 'application/x-nzb',
            'oa2'   => 'application/vnd.fujitsu.oasys2',
            'oa3'   => 'application/vnd.fujitsu.oasys3',
            'oas'   => 'application/vnd.fujitsu.oasys',
            'obd'   => 'application/x-msbinder',
            'obj'   => 'application/x-tgif',
            'oda'   => 'application/oda',
            'odb'   => 'application/vnd.oasis.opendocument.database',
            'odc'   => 'application/vnd.oasis.opendocument.chart',
            'odf'   => 'application/vnd.oasis.opendocument.formula',
            'odft'  => 'application/vnd.oasis.opendocument.formula-template',
            'odg'   => 'application/vnd.oasis.opendocument.graphics',
            'odi'   => 'application/vnd.oasis.opendocument.image',
            'odm'   => 'application/vnd.oasis.opendocument.text-master',
            'odp'   => 'application/vnd.oasis.opendocument.presentation',
            'ods'   => 'application/vnd.oasis.opendocument.spreadsheet',
            'odt'   => 'application/vnd.oasis.opendocument.text',
            'ogx'   => 'application/ogg',
            'omdoc' => 'application/omdoc+xml',
            'onepkg'    => 'application/onenote',
            'onetmp'    => 'application/onenote',
            'onetoc'    => 'application/onenote',
            'onetoc2'   => 'application/onenote',
            'opf'   => 'application/oebps-package+xml',
            'oprc'  => 'application/vnd.palm',
            'org'   => 'application/vnd.lotus-organizer',
            'osf'   => 'application/vnd.yamaha.openscoreformat',
            'osfpvg'    => 'application/vnd.yamaha.openscoreformat.osfpvg+xml',
            'otc'   => 'application/vnd.oasis.opendocument.chart-template',
            'otf'   => 'application/x-font-otf',
            'otg'   => 'application/vnd.oasis.opendocument.graphics-template',
            'oth'   => 'application/vnd.oasis.opendocument.text-web',
            'oti'   => 'application/vnd.oasis.opendocument.image-template',
            'otp'   => 'application/vnd.oasis.opendocument.presentation-template',
            'ots'   => 'application/vnd.oasis.opendocument.spreadsheet-template',
            'ott'   => 'application/vnd.oasis.opendocument.text-template',
            'oxps'  => 'application/oxps',
            'oxt'   => 'application/vnd.openofficeorg.extension',
            'p10'   => 'application/pkcs10',
            'p12'   => 'application/x-pkcs12',
            'p7b'   => 'application/x-pkcs7-certificates',
            'p7c'   => 'application/pkcs7-mime',
            'p7m'   => 'application/pkcs7-mime',
            'p7r'   => 'application/x-pkcs7-certreqresp',
            'p7s'   => 'application/pkcs7-signature',
            'p8'    => 'application/pkcs8',
            'paw'   => 'application/vnd.pawaafile',
            'pbd'   => 'application/vnd.powerbuilder6',
            'pcap'  => 'application/vnd.tcpdump.pcap',
            'pcf'   => 'application/x-font-pcf',
            'pcl'   => 'application/vnd.hp-pcl',
            'pclxl' => 'application/vnd.hp-pclxl',
            'pcurl' => 'application/vnd.curl.pcurl',
            'pdb'   => 'application/vnd.palm',
            'pdf'   => 'application/pdf',
            'pfa'   => 'application/x-font-type1',
            'pfb'   => 'application/x-font-type1',
            'pfm'   => 'application/x-font-type1',
            'pfr'   => 'application/font-tdpfr',
            'pfx'   => 'application/x-pkcs12',
            'pgn'   => 'application/x-chess-pgn',
            'pgp'   => 'application/pgp-encrypted',
            'pkg'   => 'application/octet-stream',
            'pki'   => 'application/pkixcmp',
            'pkipath'   => 'application/pkix-pkipath',
            'plb'   => 'application/vnd.3gpp.pic-bw-large',
            'plc'   => 'application/vnd.mobius.plc',
            'plf'   => 'application/vnd.pocketlearn',
            'pls'   => 'application/pls+xml',
            'pml'   => 'application/vnd.ctc-posml',
            'portpkg'   => 'application/vnd.macports.portpkg',
            'pot'   => 'application/vnd.ms-powerpoint',
            'potm'  => 'application/vnd.ms-powerpoint.template.macroenabled.12',
            'potx'  => 'application/vnd.openxmlformats-officedocument.presentationml.template',
            'ppam'  => 'application/vnd.ms-powerpoint.addin.macroenabled.12',
            'ppd'   => 'application/vnd.cups-ppd',
            'pps'   => 'application/vnd.ms-powerpoint',
            'ppsm'  => 'application/vnd.ms-powerpoint.slideshow.macroenabled.12',
            'ppsx'  => 'application/vnd.openxmlformats-officedocument.presentationml.slideshow',
            'ppt'   => 'application/vnd.ms-powerpoint',
            'pptm'  => 'application/vnd.ms-powerpoint.presentation.macroenabled.12',
            'pptx'  => 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
            'pqa'   => 'application/vnd.palm',
            'prc'   => 'application/x-mobipocket-ebook',
            'pre'   => 'application/vnd.lotus-freelance',
            'prf'   => 'application/pics-rules',
            'ps'    => 'application/postscript',
            'psb'   => 'application/vnd.3gpp.pic-bw-small',
            'psf'   => 'application/x-font-linux-psf',
            'pskcxml'   => 'application/pskc+xml',
            'ptid'  => 'application/vnd.pvi.ptid1',
            'pub'   => 'application/x-mspublisher',
            'pvb'   => 'application/vnd.3gpp.pic-bw-var',
            'pwn'   => 'application/vnd.3m.post-it-notes',
            'qam'   => 'application/vnd.epson.quickanime',
            'qbo'   => 'application/vnd.intu.qbo',
            'qfx'   => 'application/vnd.intu.qfx',
            'qps'   => 'application/vnd.publishare-delta-tree',
            'qwd'   => 'application/vnd.quark.quarkxpress',
            'qwt'   => 'application/vnd.quark.quarkxpress',
            'qxb'   => 'application/vnd.quark.quarkxpress',
            'qxd'   => 'application/vnd.quark.quarkxpress',
            'qxl'   => 'application/vnd.quark.quarkxpress',
            'qxt'   => 'application/vnd.quark.quarkxpress',
            'rar'   => 'application/x-rar-compressed',
            'rcprofile' => 'application/vnd.ipunplugged.rcprofile',
            'rdf'   => 'application/rdf+xml',
            'rdz'   => 'application/vnd.data-vision.rdz',
            'rep'   => 'application/vnd.businessobjects',
            'res'   => 'application/x-dtbresource+xml',
            'rif'   => 'application/reginfo+xml',
            'ris'   => 'application/x-research-info-systems',
            'rl'    => 'application/resource-lists+xml',
            'rld'   => 'application/resource-lists-diff+xml',
            'rm'    => 'application/vnd.rn-realmedia',
            'rms'   => 'application/vnd.jcp.javame.midlet-rms',
            'rmvb'  => 'application/vnd.rn-realmedia-vbr',
            'rnc'   => 'application/relax-ng-compact-syntax',
            'roa'   => 'application/rpki-roa',
            'rp9'   => 'application/vnd.cloanto.rp9',
            'rpss'  => 'application/vnd.nokia.radio-presets',
            'rpst'  => 'application/vnd.nokia.radio-preset',
            'rq'    => 'application/sparql-query',
            'rs'    => 'application/rls-services+xml',
            'rsd'   => 'application/rsd+xml',
            'rss'   => 'application/rss+xml',
            'rtf'   => 'application/rtf',
            'saf'   => 'application/vnd.yamaha.smaf-audio',
            'sbml'  => 'application/sbml+xml',
            'sc'    => 'application/vnd.ibm.secure-container',
            'scd'   => 'application/x-msschedule',
            'scm'   => 'application/vnd.lotus-screencam',
            'scq'   => 'application/scvp-cv-request',
            'scs'   => 'application/scvp-cv-response',
            'sda'   => 'application/vnd.stardivision.draw',
            'sdc'   => 'application/vnd.stardivision.calc',
            'sdd'   => 'application/vnd.stardivision.impress',
            'sdkd'  => 'application/vnd.solent.sdkm+xml',
            'sdkm'  => 'application/vnd.solent.sdkm+xml',
            'sdp'   => 'application/sdp',
            'sdw'   => 'application/vnd.stardivision.writer',
            'see'   => 'application/vnd.seemail',
            'seed'  => 'application/vnd.fdsn.seed',
            'sema'  => 'application/vnd.sema',
            'semd'  => 'application/vnd.semd',
            'semf'  => 'application/vnd.semf',
            'ser'   => 'application/java-serialized-object',
            'setpay'    => 'application/set-payment-initiation',
            'setreg'    => 'application/set-registration-initiation',
            'sfd-hdstx' => 'application/vnd.hydrostatix.sof-data',
            'sfs'   => 'application/vnd.spotfire.sfs',
            'sgl'   => 'application/vnd.stardivision.writer-global',
            'sh'    => 'application/x-sh',
            'shar'  => 'application/x-shar',
            'shf'   => 'application/shf+xml',
            'sig'   => 'application/pgp-signature',
            'sis'   => 'application/vnd.symbian.install',
            'sisx'  => 'application/vnd.symbian.install',
            'sit'   => 'application/x-stuffit',
            'sitx'  => 'application/x-stuffitx',
            'skd'   => 'application/vnd.koan',
            'skm'   => 'application/vnd.koan',
            'skp'   => 'application/vnd.koan',
            'skt'   => 'application/vnd.koan',
            'sldm'  => 'application/vnd.ms-powerpoint.slide.macroenabled.12',
            'sldx'  => 'application/vnd.openxmlformats-officedocument.presentationml.slide',
            'slt'   => 'application/vnd.epson.salt',
            'sm'    => 'application/vnd.stepmania.stepchart',
            'smf'   => 'application/vnd.stardivision.math',
            'smi'   => 'application/smil+xml',
            'smil'  => 'application/smil+xml',
            'smzip' => 'application/vnd.stepmania.package',
            'snf'   => 'application/x-font-snf',
            'so'    => 'application/octet-stream',
            'spc'   => 'application/x-pkcs7-certificates',
            'spf'   => 'application/vnd.yamaha.smaf-phrase',
            'spl'   => 'application/x-futuresplash',
            'spp'   => 'application/scvp-vp-response',
            'spq'   => 'application/scvp-vp-request',
            'sql'   => 'application/x-sql',
            'src'   => 'application/x-wais-source',
            'srt'   => 'application/x-subrip',
            'sru'   => 'application/sru+xml',
            'srx'   => 'application/sparql-results+xml',
            'ssdl'  => 'application/ssdl+xml',
            'sse'   => 'application/vnd.kodak-descriptor',
            'ssf'   => 'application/vnd.epson.ssf',
            'ssml'  => 'application/ssml+xml',
            'st'    => 'application/vnd.sailingtracker.track',
            'stc'   => 'application/vnd.sun.xml.calc.template',
            'std'   => 'application/vnd.sun.xml.draw.template',
            'stf'   => 'application/vnd.wt.stf',
            'sti'   => 'application/vnd.sun.xml.impress.template',
            'stk'   => 'application/hyperstudio',
            'stl'   => 'application/vnd.ms-pki.stl',
            'str'   => 'application/vnd.pg.format',
            'stw'   => 'application/vnd.sun.xml.writer.template',
            'sus'   => 'application/vnd.sus-calendar',
            'susp'  => 'application/vnd.sus-calendar',
            'sv4cpio'   => 'application/x-sv4cpio',
            'sv4crc'    => 'application/x-sv4crc',
            'svc'   => 'application/vnd.dvb.service',
            'svd'   => 'application/vnd.svd',
            'swa'   => 'application/x-director',
            'swf'   => 'application/x-shockwave-flash',
            'swi'   => 'application/vnd.aristanetworks.swi',
            'sxc'   => 'application/vnd.sun.xml.calc',
            'sxd'   => 'application/vnd.sun.xml.draw',
            'sxg'   => 'application/vnd.sun.xml.writer.global',
            'sxi'   => 'application/vnd.sun.xml.impress',
            'sxm'   => 'application/vnd.sun.xml.math',
            'sxw'   => 'application/vnd.sun.xml.writer',
            't3'    => 'application/x-t3vm-image',
            'taglet'    => 'application/vnd.mynfc',
            'tao'   => 'application/vnd.tao.intent-module-archive',
            'tar'   => 'application/x-tar',
            'tcap'  => 'application/vnd.3gpp2.tcap',
            'tcl'   => 'application/x-tcl',
            'teacher'   => 'application/vnd.smart.teacher',
            'tei'   => 'application/tei+xml',
            'teicorpus' => 'application/tei+xml',
            'tex'   => 'application/x-tex',
            'texi'  => 'application/x-texinfo',
            'texinfo'   => 'application/x-texinfo',
            'tfi'   => 'application/thraud+xml',
            'tfm'   => 'application/x-tex-tfm',
            'thmx'  => 'application/vnd.ms-officetheme',
            'tmo'   => 'application/vnd.tmobile-livetv',
            'torrent'   => 'application/x-bittorrent',
            'tpl'   => 'application/vnd.groove-tool-template',
            'tpt'   => 'application/vnd.trid.tpt',
            'tra'   => 'application/vnd.trueapp',
            'trm'   => 'application/x-msterminal',
            'tsd'   => 'application/timestamped-data',
            'ttc'   => 'application/x-font-ttf',
            'ttf'   => 'application/x-font-ttf',
            'twd'   => 'application/vnd.simtech-mindmapper',
            'twds'  => 'application/vnd.simtech-mindmapper',
            'txd'   => 'application/vnd.genomatix.tuxedo',
            'txf'   => 'application/vnd.mobius.txf',
            'u32'   => 'application/x-authorware-bin',
            'udeb'  => 'application/x-debian-package',
            'ufd'   => 'application/vnd.ufdl',
            'ufdl'  => 'application/vnd.ufdl',
            'ulx'   => 'application/x-glulx',
            'umj'   => 'application/vnd.umajin',
            'unityweb'  => 'application/vnd.unity',
            'uoml'  => 'application/vnd.uoml+xml',
            'ustar' => 'application/x-ustar',
            'utz'   => 'application/vnd.uiq.theme',
            'uvd'   => 'application/vnd.dece.data',
            'uvf'   => 'application/vnd.dece.data',
            'uvt'   => 'application/vnd.dece.ttml+xml',
            'uvvd'  => 'application/vnd.dece.data',
            'uvvf'  => 'application/vnd.dece.data',
            'uvvt'  => 'application/vnd.dece.ttml+xml',
            'uvvx'  => 'application/vnd.dece.unspecified',
            'uvvz'  => 'application/vnd.dece.zip',
            'uvx'   => 'application/vnd.dece.unspecified',
            'uvz'   => 'application/vnd.dece.zip',
            'vcd'   => 'application/x-cdlink',
            'vcg'   => 'application/vnd.groove-vcard',
            'vcx'   => 'application/vnd.vcx',
            'vis'   => 'application/vnd.visionary',
            'vor'   => 'application/vnd.stardivision.writer',
            'vox'   => 'application/x-authorware-bin',
            'vsd'   => 'application/vnd.visio',
            'vsf'   => 'application/vnd.vsf',
            'vss'   => 'application/vnd.visio',
            'vst'   => 'application/vnd.visio',
            'vsw'   => 'application/vnd.visio',
            'vxml'  => 'application/voicexml+xml',
            'w3d'   => 'application/x-director',
            'wad'   => 'application/x-doom',
            'wbs'   => 'application/vnd.criticaltools.wbs+xml',
            'wbxml' => 'application/vnd.wap.wbxml',
            'wcm'   => 'application/vnd.ms-works',
            'wdb'   => 'application/vnd.ms-works',
            'wg'    => 'application/vnd.pmi.widget',
            'wgt'   => 'application/widget',
            'wks'   => 'application/vnd.ms-works',
            'wmd'   => 'application/x-ms-wmd',
            'wmf'   => 'application/x-msmetafile',
            'wmlc'  => 'application/vnd.wap.wmlc',
            'wmlsc' => 'application/vnd.wap.wmlscriptc',
            'wmz'   => 'application/x-msmetafile',
            'woff'  => 'application/x-font-woff',
            'wpd'   => 'application/vnd.wordperfect',
            'wpl'   => 'application/vnd.ms-wpl',
            'wps'   => 'application/vnd.ms-works',
            'wqd'   => 'application/vnd.wqd',
            'wri'   => 'application/x-mswrite',
            'wsdl'  => 'application/wsdl+xml',
            'wspolicy'  => 'application/wspolicy+xml',
            'wtb'   => 'application/vnd.webturbo',
            'x32'   => 'application/x-authorware-bin',
            'xaml'  => 'application/xaml+xml',
            'xap'   => 'application/x-silverlight-app',
            'xar'   => 'application/vnd.xara',
            'xbap'  => 'application/x-ms-xbap',
            'xbd'   => 'application/vnd.fujixerox.docuworks.binder',
            'xdf'   => 'application/xcap-diff+xml',
            'xdm'   => 'application/vnd.syncml.dm+xml',
            'xdp'   => 'application/vnd.adobe.xdp+xml',
            'xdssc' => 'application/dssc+xml',
            'xdw'   => 'application/vnd.fujixerox.docuworks',
            'xenc'  => 'application/xenc+xml',
            'xer'   => 'application/patch-ops-error+xml',
            'xfdf'  => 'application/vnd.adobe.xfdf',
            'xfdl'  => 'application/vnd.xfdl',
            'xht'   => 'application/xhtml+xml',
            'xhtml' => 'application/xhtml+xml',
            'xhvml' => 'application/xv+xml',
            'xla'   => 'application/vnd.ms-excel',
            'xlam'  => 'application/vnd.ms-excel.addin.macroenabled.12',
            'xlc'   => 'application/vnd.ms-excel',
            'xlf'   => 'application/x-xliff+xml',
            'xlm'   => 'application/vnd.ms-excel',
            'xls'   => 'application/vnd.ms-excel',
            'xlsb'  => 'application/vnd.ms-excel.sheet.binary.macroenabled.12',
            'xlsm'  => 'application/vnd.ms-excel.sheet.macroenabled.12',
            'xlsx'  => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
            'xlt'   => 'application/vnd.ms-excel',
            'xltm'  => 'application/vnd.ms-excel.template.macroenabled.12',
            'xltx'  => 'application/vnd.openxmlformats-officedocument.spreadsheetml.template',
            'xlw'   => 'application/vnd.ms-excel',
            'xml'   => 'application/xml',
            'xo'    => 'application/vnd.olpc-sugar',
            'xop'   => 'application/xop+xml',
            'xpi'   => 'application/x-xpinstall',
            'xpl'   => 'application/xproc+xml',
            'xpr'   => 'application/vnd.is-xpr',
            'xps'   => 'application/vnd.ms-xpsdocument',
            'xpw'   => 'application/vnd.intercon.formnet',
            'xpx'   => 'application/vnd.intercon.formnet',
            'xsl'   => 'application/xml',
            'xslt'  => 'application/xslt+xml',
            'xsm'   => 'application/vnd.syncml+xml',
            'xspf'  => 'application/xspf+xml',
            'xul'   => 'application/vnd.mozilla.xul+xml',
            'xvm'   => 'application/xv+xml',
            'xvml'  => 'application/xv+xml',
            'xz'    => 'application/x-xz',
            'yang'  => 'application/yang',
            'yin'   => 'application/yin+xml',
            'z1'    => 'application/x-zmachine',
            'z2'    => 'application/x-zmachine',
            'z3'    => 'application/x-zmachine',
            'z4'    => 'application/x-zmachine',
            'z5'    => 'application/x-zmachine',
            'z6'    => 'application/x-zmachine',
            'z7'    => 'application/x-zmachine',
            'z8'    => 'application/x-zmachine',
            'zaz'   => 'application/vnd.zzazz.deck+xml',
            'zip'   => 'application/zip',
            'zir'   => 'application/vnd.zul',
            'zirz'  => 'application/vnd.zul',
            'zmm'   => 'application/vnd.handheld-entertainment+xml',

            // "audio/*"
            'aac'   => 'audio/x-aac',
            'adp'   => 'audio/adpcm',
            'aif'   => 'audio/x-aiff',
            'aifc'  => 'audio/x-aiff',
            'aiff'  => 'audio/x-aiff',
            'au'    => 'audio/basic',
            'caf'   => 'audio/x-caf',
            'dra'   => 'audio/vnd.dra',
            'dts'   => 'audio/vnd.dts',
            'dtshd' => 'audio/vnd.dts.hd',
            'eol'   => 'audio/vnd.digital-winds',
            'flac'  => 'audio/x-flac',
            'kar'   => 'audio/midi',
            'lvp'   => 'audio/vnd.lucent.voice',
            'm2a'   => 'audio/mpeg',
            'm3a'   => 'audio/mpeg',
            'm3u'   => 'audio/x-mpegurl',
            'mid'   => 'audio/midi',
            'midi'  => 'audio/midi',
            'mka'   => 'audio/x-matroska',
            'mp2'   => 'audio/mpeg',
            'mp2a'  => 'audio/mpeg',
            'mp3'   => 'audio/mpeg',
            'mp4a'  => 'audio/mp4',
            'mpga'  => 'audio/mpeg',
            'oga'   => 'audio/ogg',
            'ogg'   => 'audio/ogg',
            'pya'   => 'audio/vnd.ms-playready.media.pya',
            'ra'    => 'audio/x-pn-realaudio',
            'ram'   => 'audio/x-pn-realaudio',
            'rip'   => 'audio/vnd.rip',
            'rmi'   => 'audio/midi',
            'rmp'   => 'audio/x-pn-realaudio-plugin',
            's3m'   => 'audio/s3m',
            'sil'   => 'audio/silk',
            'snd'   => 'audio/basic',
            'spx'   => 'audio/ogg',
            'uva'   => 'audio/vnd.dece.audio',
            'uvva'  => 'audio/vnd.dece.audio',
            'wav'   => 'audio/x-wav',
            'wax'   => 'audio/x-ms-wax',
            'weba'  => 'audio/webm',
            'wma'   => 'audio/x-ms-wma',
            'xm'    => 'audio/xm',

            // "chemical/*"
            'cdx'   => 'chemical/x-cdx',
            'cif'   => 'chemical/x-cif',
            'cmdf'  => 'chemical/x-cmdf',
            'cml'   => 'chemical/x-cml',
            'csml'  => 'chemical/x-csml',
            'xyz'   => 'chemical/x-xyz',

            // "image/*"
            '3ds'   => 'image/x-3ds',
            'bmp'   => 'image/bmp',
            'btif'  => 'image/prs.btif',
            'cgm'   => 'image/cgm',
            'cmx'   => 'image/x-cmx',
            'djv'   => 'image/vnd.djvu',
            'djvu'  => 'image/vnd.djvu',
            'dwg'   => 'image/vnd.dwg',
            'dxf'   => 'image/vnd.dxf',
            'fbs'   => 'image/vnd.fastbidsheet',
            'fh'    => 'image/x-freehand',
            'fh4'   => 'image/x-freehand',
            'fh5'   => 'image/x-freehand',
            'fh7'   => 'image/x-freehand',
            'fhc'   => 'image/x-freehand',
            'fpx'   => 'image/vnd.fpx',
            'fst'   => 'image/vnd.fst',
            'g3'    => 'image/g3fax',
            'gif'   => 'image/gif',
            'ico'   => 'image/x-icon',
            'ief'   => 'image/ief',
            'jpe'   => 'image/jpeg',
            'jpeg'  => 'image/jpeg',
            'jpg'   => 'image/jpeg',
            'ktx'   => 'image/ktx',
            'mdi'   => 'image/vnd.ms-modi',
            'mmr'   => 'image/vnd.fujixerox.edmics-mmr',
            'npx'   => 'image/vnd.net-fpx',
            'pbm'   => 'image/x-portable-bitmap',
            'pct'   => 'image/x-pict',
            'pcx'   => 'image/x-pcx',
            'pgm'   => 'image/x-portable-graymap',
            'pic'   => 'image/x-pict',
            'png'   => 'image/png',
            'pnm'   => 'image/x-portable-anymap',
            'ppm'   => 'image/x-portable-pixmap',
            'psd'   => 'image/vnd.adobe.photoshop',
            'ras'   => 'image/x-cmu-raster',
            'rgb'   => 'image/x-rgb',
            'rlc'   => 'image/vnd.fujixerox.edmics-rlc',
            'sgi'   => 'image/sgi',
            'sid'   => 'image/x-mrsid-image',
            'sub'   => 'text/vnd.dvb.subtitle',
            'svg'   => 'image/svg+xml',
            'svgz'  => 'image/svg+xml',
            'tga'   => 'image/x-tga',
            'tif'   => 'image/tiff',
            'tiff'  => 'image/tiff',
            'uvg'   => 'image/vnd.dece.graphic',
            'uvi'   => 'image/vnd.dece.graphic',
            'uvvg'  => 'image/vnd.dece.graphic',
            'uvvi'  => 'image/vnd.dece.graphic',
            'wbmp'  => 'image/vnd.wap.wbmp',
            'wdp'   => 'image/vnd.ms-photo',
            'webp'  => 'image/webp',
            'xbm'   => 'image/x-xbitmap',
            'xif'   => 'image/vnd.xiff',
            'xpm'   => 'image/x-xpixmap',
            'xwd'   => 'image/x-xwindowdump',

            // "message/*"
            'eml'   => 'message/rfc822',
            'mime'  => 'message/rfc822',

            // "model/*"
            'dae'   => 'model/vnd.collada+xml',
            'dwf'   => 'model/vnd.dwf',
            'gdl'   => 'model/vnd.gdl',
            'gtw'   => 'model/vnd.gtw',
            'iges'  => 'model/iges',
            'igs'   => 'model/iges',
            'mesh'  => 'model/mesh',
            'msh'   => 'model/mesh',
            'mts'   => 'model/vnd.mts',
            'silo'  => 'model/mesh',
            'vrml'  => 'model/vrml',
            'vtu'   => 'model/vnd.vtu',
            'wrl'   => 'model/vrml',
            'x3d'   => 'model/x3d+xml',
            'x3db'  => 'model/x3d+binary',
            'x3dbz' => 'model/x3d+binary',
            'x3dv'  => 'model/x3d+vrml',
            'x3dvz' => 'model/x3d+vrml',
            'x3dz'  => 'model/x3d+xml',

            // "text/*"
            '3dml'  => 'text/vnd.in3d.3dml',
            'appcache' => 'text/cache-manifest',
            'asm'   => 'text/x-asm',
            'c'     => 'text/x-c',
            'cc'    => 'text/x-c',
            'conf'  => 'text/plain',
            'cpp'   => 'text/x-c',
            'css'   => 'text/css',
            'csv'   => 'text/csv',
            'curl'  => 'text/vnd.curl',
            'cxx'   => 'text/x-c',
            'dcurl' => 'text/vnd.curl.dcurl',
            'def'   => 'text/plain',
            'dic'   => 'text/x-c',
            'dsc'   => 'text/prs.lines.tag',
            'etx'   => 'text/x-setext',
            'f'     => 'text/x-fortran',
            'f77'   => 'text/x-fortran',
            'f90'   => 'text/x-fortran',
            'flx'   => 'text/vnd.fmi.flexstor',
            'fly'   => 'text/vnd.fly',
            'for'   => 'text/x-fortran',
            'gv'    => 'text/vnd.graphviz',
            'h'     => 'text/x-c',
            'hh'    => 'text/x-c',
            'htm'   => 'text/html',
            'html'  => 'text/html',
            'ics'   => 'text/calendar',
            'ifb'   => 'text/calendar',
            'in'    => 'text/plain',
            'jad'   => 'text/vnd.sun.j2me.app-descriptor',
            'java'  => 'text/x-java-source',
            'list'  => 'text/plain',
            'log'   => 'text/plain',
            'man'   => 'text/troff',
            'mcurl' => 'text/vnd.curl.mcurl',
            'me'    => 'text/troff',
            'ms'    => 'text/troff',
            'n3'    => 'text/n3',
            'nfo'   => 'text/x-nfo',
            'opml'  => 'text/x-opml',
            'p'     => 'text/x-pascal',
            'pas'   => 'text/x-pascal',
            'roff'  => 'text/troff',
            'rtx'   => 'text/richtext',
            's'     => 'text/x-asm',
            'scurl' => 'text/vnd.curl.scurl',
            'sfv'   => 'text/x-sfv',
            'sgm'   => 'text/sgml',
            'sgml'  => 'text/sgml',
            'spot'  => 'text/vnd.in3d.spot',
            't'     => 'text/troff',
            'text'  => 'text/plain',
            'tr'    => 'text/troff',
            'tsv'   => 'text/tab-separated-values',
            'ttl'   => 'text/turtle',
            'txt'   => 'text/plain',
            'uri'   => 'text/uri-list',
            'uris'  => 'text/uri-list',
            'urls'  => 'text/uri-list',
            'uu'    => 'text/x-uuencode',
            'vcard' => 'text/vcard',
            'vcf'   => 'text/x-vcard',
            'vcs'   => 'text/x-vcalendar',
            'wml'   => 'text/vnd.wap.wml',
            'wmls'  => 'text/vnd.wap.wmlscript',

            // "video/*"
            '3g2'   => 'video/3gpp2',
            '3gp'   => 'video/3gpp',
            'asf'   => 'video/x-ms-asf',
            'asx'   => 'video/x-ms-asf',
            'avi'   => 'video/x-msvideo',
            'dvb'   => 'video/vnd.dvb.file',
            'f4v'   => 'video/x-f4v',
            'fli'   => 'video/x-fli',
            'flv'   => 'video/x-flv',
            'fvt'   => 'video/vnd.fvt',
            'h261'  => 'video/h261',
            'h263'  => 'video/h263',
            'h264'  => 'video/h264',
            'jpgm'  => 'video/jpm',
            'jpgv'  => 'video/jpeg',
            'jpm'   => 'video/jpm',
            'm1v'   => 'video/mpeg',
            'm2v'   => 'video/mpeg',
            'm4u'   => 'video/vnd.mpegurl',
            'm4v'   => 'video/x-m4v',
            'mj2'   => 'video/mj2',
            'mjp2'  => 'video/mj2',
            'mk3d'  => 'video/x-matroska',
            'mks'   => 'video/x-matroska',
            'mkv'   => 'video/x-matroska',
            'mng'   => 'video/x-mng',
            'mov'   => 'video/quicktime',
            'movie' => 'video/x-sgi-movie',
            'mp4'   => 'video/mp4',
            'mp4v'  => 'video/mp4',
            'mpe'   => 'video/mpeg',
            'mpeg'  => 'video/mpeg',
            'mpg'   => 'video/mpeg',
            'mpg4'  => 'video/mp4',
            'mxu'   => 'video/vnd.mpegurl',
            'ogv'   => 'video/ogg',
            'pyv'   => 'video/vnd.ms-playready.media.pyv',
            'qt'    => 'video/quicktime',
            'smv'   => 'video/x-smv',
            'uvh'   => 'video/vnd.dece.hd',
            'uvm'   => 'video/vnd.dece.mobile',
            'uvp'   => 'video/vnd.dece.pd',
            'uvs'   => 'video/vnd.dece.sd',
            'uvu'   => 'video/vnd.uvvu.mp4',
            'uvv'   => 'video/vnd.dece.video',
            'uvvh'  => 'video/vnd.dece.hd',
            'uvvm'  => 'video/vnd.dece.mobile',
            'uvvp'  => 'video/vnd.dece.pd',
            'uvvs'  => 'video/vnd.dece.sd',
            'uvvu'  => 'video/vnd.uvvu.mp4',
            'uvvv'  => 'video/vnd.dece.video',
            'viv'   => 'video/vnd.vivo',
            'vob'   => 'video/x-ms-vob',
            'webm'  => 'video/webm',
            'wm'    => 'video/x-ms-wm',
            'wmv'   => 'video/x-ms-wmv',
            'wmx'   => 'video/x-ms-wmx',
            'wvx'   => 'video/x-ms-wvx',

            // "x-conference/*"
            'ice'   => 'x-conference/x-cooltalk'
        );
    }
}
